import Footer from "./components/footser";
import Header from "./components/header";
import "./globals.css";
import { Inter } from "next/font/google";
//see how fonts are imported from google fonts

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Ismail Kayadelen | Portfolio",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
              <Header />
              {children}
              <Footer />
              </body>
        </html>
    );
}
