import React from "react";
import Footer from "./components/footer/footer";
import Header from "./components/header/header";
import { Quicksand } from "next/font/google";
import "./globals.css";

const font = Quicksand({ subsets: ["latin"] });

export const metadata = {
    title: "Ismail Kayadelen | Portfolio",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en" className="scroll-smooth">
            <body className={font.className}>
                <Header/>
                {children}
                <Footer />
            </body>
        </html>
    );
}
